version: '3'

services:
  realsense:
    image: husarion/realsense:humble
    network_mode: host
    ipc: host
    tty: true
    environment:
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}
      - RMW_/IMPLEMENTATION=${RMW_IMPLEMENTATION:-rmw_fastrtps_cpp}
    volumes:
      - /dev:/dev
    privileged: true
    command: ros2 launch realsense2_camera rs_launch.py pointcloud.enable:=true

  rviz2:
    image: husarion/rviz2:humble
    network_mode: host
    ipc: host
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./default.rviz:/root/.rviz2/default.rviz
    environment:
      - DISPLAY=${DISPLAY:?err}
      - LIBGL_ALWAYS_SOFTWARE=1
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}
      - RMW_/IMPLEMENTATION=${RMW_IMPLEMENTATION:-rmw_fastrtps_cpp}
